name: Build and Push Docker Images (Django + Nginx)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  security-events: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML with tidy (index.html)
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -qe ./mysite/singlepage/templates/singlepage/index.html || true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      #### DJANGO IMAGE ####
      - name: Build Django image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/django ./mysite

      - name: Push Django image
        if: github.event_name != 'pull_request'
        run: docker push ${{ vars.DOCKER_USERNAME }}/django

      - name: Scan Django image (SARIF)
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKER_USERNAME }}/django
          format: sarif
          output: django-trivy.sarif
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Django SARIF to GitHub
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: django-trivy.sarif

      - name: Upload Django SARIF as artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: django-trivy-report
          path: django-trivy.sarif

      - name: Trivy CRITICAL scan (Django)
        if: github.event_name != 'pull_request'
        run: |
          trivy image --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            --format table \
            --detection-priority precise \
            ${{ vars.DOCKER_USERNAME }}/django

      #### NGINX IMAGE ####
      - name: Build Nginx image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/nginx ./nginx

      - name: Push Nginx image
        if: github.event_name != 'pull_request'
        run: docker push ${{ vars.DOCKER_USERNAME }}/nginx

      - name: Scan Nginx image (SARIF)
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKER_USERNAME }}/nginx
          format: sarif
          output: nginx-trivy.sarif
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Nginx SARIF to GitHub
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: nginx-trivy.sarif

      - name: Upload Nginx SARIF as artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: nginx-trivy-report
          path: nginx-trivy.sarif

      - name: Trivy CRITICAL scan (Nginx)
        if: github.event_name != 'pull_request'
        run: |
          trivy image --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            --format table \
            --detection-priority precise \
            ${{ vars.DOCKER_USERNAME }}/nginx

      #### SLACK NOTIFICATION ON FAILURE ####
      - name: Notify Slack on failure
        if: failure() && github.event_name != 'pull_request'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚨 *GitHub Actions:* Falló el build o el análisis de seguridad de las imágenes Django o NGINX.\n🔍 Revisa los logs 👉 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

