name: Build and Push Docker Imagev2

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  security-events: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML with tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy
          tidy -qe index.html

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/imagev2
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker imagev2
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # EXTRA: Extraer el primer tag (ej: latest) para Trivy
      - name: Extract first tag for Trivy
        id: tag
        run: |
          first_tag=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "tag=$first_tag" >> tag_output.txt
          cat tag_output.txt >> $GITHUB_OUTPUT

      # (1) Escaneo y generación de reporte SARIF
      - name: Scan Docker image with Trivy (SARIF)
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.tag.outputs.tag }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
          ignore-unfixed: true

      - name: Upload Trivy SARIF report to GitHub
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy SARIF report as downloadable artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.sarif

      # (2) Escaneo estricto que puede fallar si hay vulnerabilidades críticas
      - name: Trivy Security Gate (fail on CRITICAL)
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.tag.outputs.tag }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL

      # (3) Notificación a Slack si falla
      - name: Notify Slack on failure
        if: failure() && github.event_name != 'pull_request'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚨 *GitHub Actions:* Build or security scan *failed* for imagev2.\n🔍 Revisa los logs 👉 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
